name: Ruby
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    env:
      BUNDLE_VERSION: system
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, ruby: '3.2'}
          - {os: ubuntu-latest, ruby: '3.3'}
          - {os: ubuntu-latest, ruby: '3.4'}
          - {os: ubuntu-latest, ruby: '4.0'}
          - {os: macos-latest, ruby: '3.4'}
          - {os: windows-latest, ruby: '3.4'}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@984c0c890880bbf811283d6f09c4607c62d210a4 # v1.323.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true
      - run: bundle exec rake test
      - run: bundle exec rbs -I sig -r stringio validate
      - run: gem build --strict xamidimura.gemspec
